// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webApi6
{
    public partial class TblCartStatus
    {
        public TblCartStatus()
        {
            TblCart = new HashSet<TblCart>();
        }

        public int CartStatusId { get; set; }
        public string CartStatus { get; set; }

        public virtual ICollection<TblCart> TblCart { get; set; }
    }
}