// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webApi6
{
    public partial class TblMembers
    {
        public TblMembers()
        {
            TblCart = new HashSet<TblCart>();
            TblIotUsers = new HashSet<TblIotUsers>();
            TblShippingDetails = new HashSet<TblShippingDetails>();
        }

        public int MemberId { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? GroupAdmin { get; set; }
        public string UserName { get; set; }

        public virtual ICollection<TblCart> TblCart { get; set; }
        public virtual ICollection<TblIotUsers> TblIotUsers { get; set; }
        public virtual ICollection<TblShippingDetails> TblShippingDetails { get; set; }
    }
}