// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webApi6
{
    public partial class TblRoles
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
    }
}